# Global config
global:
  scrape_interval:     240s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 240s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 120s  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'snmp'
    static_configs:
    - targets: ['cisco1']
    - targets: ['cisco2']
    metrics_path: /snmp
    params:
      module: ['ciscosw']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116
  - job_name: 'snmpj'
    static_configs:
    - targets: ['juniper1']
    metrics_path: /snmp
    params:
      module: ['junipersw']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116
